// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKtlhhb6VxK6DahR5gvpTLRMcXSyP6BxQ',
    appId: '1:96343924525:web:8d41105ec46caa50df7da4',
    messagingSenderId: '96343924525',
    projectId: 'online-perfume-app-fyp',
    authDomain: 'online-perfume-app-fyp.firebaseapp.com',
    storageBucket: 'online-perfume-app-fyp.firebasestorage.app',
    measurementId: 'G-KV446VGEYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0XGeYe9Q6Fsrj8NbeG7dMqyjY1O68rfY',
    appId: '1:96343924525:android:5fcb64840adb3f7adf7da4',
    messagingSenderId: '96343924525',
    projectId: 'online-perfume-app-fyp',
    storageBucket: 'online-perfume-app-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOMmpFi84YpXM8_jzzsgCBSKD26CaypK8',
    appId: '1:96343924525:ios:72a61f8270bbe23cdf7da4',
    messagingSenderId: '96343924525',
    projectId: 'online-perfume-app-fyp',
    storageBucket: 'online-perfume-app-fyp.firebasestorage.app',
    iosBundleId: 'com.example.onlinePerfumeAppFyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKtlhhb6VxK6DahR5gvpTLRMcXSyP6BxQ',
    appId: '1:96343924525:web:0a6a682398e2c795df7da4',
    messagingSenderId: '96343924525',
    projectId: 'online-perfume-app-fyp',
    authDomain: 'online-perfume-app-fyp.firebaseapp.com',
    storageBucket: 'online-perfume-app-fyp.firebasestorage.app',
    measurementId: 'G-PRNYZ0K9NS',
  );
}
